Machine Learning Zoomcamo

1.7 Intro to Numpy

Plan:

* Creating Arrays
* Multi Dimentional Arrays
* Randomly Generated Arrays
* Element-wise operation
    * Comparison Operations
    * Logical Operations
* Summarizing Operations


In [4]:
import numpy as np

In [5]:
np

<module 'numpy' from '/home/codespace/.local/lib/python3.12/site-packages/numpy/__init__.py'>

In [7]:
## Creating Arrays
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [8]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [11]:
np.full(10, 2.3)

array([2.3, 2.3, 2.3, 2.3, 2.3, 2.3, 2.3, 2.3, 2.3, 2.3])

In [12]:
a = np.array([1,2,3,5,7,12])

In [13]:
a

array([ 1,  2,  3,  5,  7, 12])

In [14]:
a[3]

np.int64(5)

In [15]:
a[3] = 10

In [16]:
a

array([ 1,  2,  3, 10,  7, 12])

In [17]:
np.arange(4,15)

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [18]:
np.linspace(0,2,10)

array([0.        , 0.22222222, 0.44444444, 0.66666667, 0.88888889,
       1.11111111, 1.33333333, 1.55555556, 1.77777778, 2.        ])

Multi-dimentional arrays

In [19]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [21]:
np.array([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Randomly generated arrays

In [28]:
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [29]:
np.random.seed(2)
np.random.randn(5,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [30]:
np.random.seed(2)
100 * np.random.rand(5,2)

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [32]:
np.random.seed(2)
np.random.randint(low=0, high = 100, size=(5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

Element-wise operations

In [34]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [36]:
a + 1

array([1, 2, 3, 4, 5])

In [37]:
a *100

array([  0, 100, 200, 300, 400])

In [39]:
10 + (a * 2) ** 2

array([10, 14, 26, 46, 74])

Comparison Operations